### ISSUE TITLE
Wireguard installation fails on azure/ubuntu image

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner#607]
**Which jobs are failing**:
wireguard related

**Which test(s) are failing**:
system setup/install of wireguard modules

**Since when has it been failing**:
2 days back.

**Testgrid link**:
https://github.com/submariner-io/submariner/runs/716790061?check_suite_focus=true#step:3:181

**Reason for failure**:
```
2020-05-28T12:53:36.3810375Z Error! Bad return status for module build on kernel: 5.3.0-1020-azure (x86_64)
2020-05-28T12:53:36.3810853Z Consult /var/lib/dkms/wireguard/1.0.20200520/build/make.log for more information.
2020-05-28T12:53:36.3918950Z Setting up wireguard (1.0.20200513-1~18.04) ...
2020-05-28T12:53:36.3974644Z Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
2020-05-28T12:53:39.8095946Z DKMS make.log for wireguard-1.0.20200520 for kernel 5.3.0-1020-azure (x86_64)
2020-05-28T12:53:39.8096174Z Thu May 28 12:53:28 UTC 2020
2020-05-28T12:53:39.8096477Z make: Entering directory '/usr/src/linux-headers-5.3.0-1020-azure'
2020-05-28T12:53:39.8096588Z   CC [M]  /var/lib/dkms/wireguard/1.0.20200520/build/main.o
2020-05-28T12:53:39.8096681Z   CC [M]  /var/lib/dkms/wireguard/1.0.20200520/build/noise.o
2020-05-28T12:53:39.8096937Z In file included from /var/lib/dkms/wireguard/1.0.20200520/build/noise.c:10:0:
2020-05-28T12:53:39.8097190Z /var/lib/dkms/wireguard/1.0.20200520/build/queueing.h: In function â€˜wg_reset_packetâ€™:
2020-05-28T12:53:39.8097543Z /var/lib/dkms/wireguard/1.0.20200520/build/queueing.h:115:2: error: implicit declaration of function â€˜skb_reset_redirectâ€™; did you mean â€˜skb_do_redirectâ€™? [-Werror=implicit-function-declaration]
2020-05-28T12:53:39.8097664Z   skb_reset_redirect(skb);
2020-05-28T12:53:39.8097753Z   ^~~~~~~~~~~~~~~~~~
2020-05-28T12:53:39.8097837Z   skb_do_redirect
2020-05-28T12:53:39.8097911Z In file included from /var/lib/dkms/wireguard/1.0.20200520/build/main.c:9:0:
2020-05-28T12:53:39.8098247Z /var/lib/dkms/wireguard/1.0.20200520/build/queueing.h: In function â€˜wg_reset_packetâ€™:
2020-05-28T12:53:39.8098805Z /var/lib/dkms/wireguard/1.0.20200520/build/queueing.h:115:2: error: implicit declaration of function â€˜skb_reset_redirectâ€™; did you mean â€˜skb_do_redirectâ€™? [-Werror=implicit-function-declaration]
2020-05-28T12:53:39.8098922Z   skb_reset_redirect(skb);
2020-05-28T12:53:39.8099232Z   ^~~~~~~~~~~~~~~~~~
2020-05-28T12:53:39.8099301Z   skb_do_redirect
2020-05-28T12:53:39.8099392Z cc1: some warnings being treated as errors
2020-05-28T12:53:39.8099678Z scripts/Makefile.build:288: recipe for target '/var/lib/dkms/wireguard/1.0.20200520/build/main.o' failed
2020-05-28T12:53:39.8099792Z make[1]: *** [/var/lib/dkms/wireguard/1.0.20200520/build/main.o] Error 1
2020-05-28T12:53:39.8099874Z make[1]: *** Waiting for unfinished jobs....
2020-05-28T12:53:39.8099966Z cc1: some warnings being treated as errors
2020-05-28T12:53:39.8100247Z scripts/Makefile.build:288: recipe for target '/var/lib/dkms/wireguard/1.0.20200520/build/noise.o' failed
2020-05-28T12:53:39.8100620Z make[1]: *** [/var/lib/dkms/wireguard/1.0.20200520/build/noise.o] Error 1
2020-05-28T12:53:39.8100939Z Makefile:1656: recipe for target '_module_/var/lib/dkms/wireguard/1.0.20200520/build' failed
2020-05-28T12:53:39.8101192Z make: *** [_module_/var/lib/dkms/wireguard/1.0.20200520/build] Error 2
2020-05-28T12:53:39.8101594Z make: Leaving directory '/usr/src/linux-headers-5.3.0-1020-azure'
2020-05-28T12:54:46.5390434Z Downloading queuing.h to /usr/src/wireguard-1.0.20200520
2020-05-28T12:54:46.5567994Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2020-05-28T12:54:46.5569077Z                                  Dload  Upload   Total   Spent    Left  Speed
2020-05-28T12:54:46.5569351Z 
2020-05-28T12:54:46.8639156Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2020-05-28T12:54:46.8639484Z 100  6272  100  6272    0     0  20429      0 --:--:-- --:--:-- --:--:-- 20429
2020-05-28T12:54:46.9873164Z Reading package lists...
2020-05-28T12:54:47.1437708Z Building dependency tree...
2020-05-28T12:54:47.1456934Z Reading state information...
2020-05-28T12:54:47.3584753Z linux-headers-5.3.0-1020-azure is already the newest version (5.3.0-1020.21~18.04.1).
2020-05-28T12:54:47.3585879Z wireguard is already the newest version (1.0.20200513-1~18.04).
2020-05-28T12:54:47.3586334Z 0 upgraded, 0 newly installed, 0 to remove and 78 not upgraded.
2020-05-28T12:54:47.6338124Z 
2020-05-28T12:54:47.6339132Z ------------------------------
2020-05-28T12:54:47.6339390Z Deleting module version: 1.0.20200520
2020-05-28T12:54:47.6339538Z completely from the DKMS tree.
2020-05-28T12:54:47.6339800Z ------------------------------
2020-05-28T12:54:47.6379236Z Done.
2020-05-28T12:54:47.7639238Z Loading new wireguard-1.0.20200520 DKMS files...
2020-05-28T12:54:47.8767972Z Building for 5.3.0-1020-azure
2020-05-28T12:54:47.9053535Z Building initial module for 5.3.0-1020-azure
2020-05-28T12:54:52.3321182Z ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/wireguard-dkms.0.crash'
2020-05-28T12:54:52.3553669Z Error! Bad return status for module build on kernel: 5.3.0-1020-azure (x86_64)
2020-05-28T12:54:52.3554296Z Consult /var/lib/dkms/wireguard/1.0.20200520/build/make.log for more information.
2020-05-28T12:54:52.4697738Z modprobe: FATAL: Module wireguard not found in directory /lib/modules/5.3.0-1020-azure
2020-05-28T12:54:52.4716711Z ##[error]Process completed with exit code 1.
2020-05-28T12:54:52.4762372Z ##[group]Run df -h
2020-05-28T12:54:52.4762561Z [36;1mdf -h[0m
```
**Anything else we need to know**:
Life is short, enjoy it! ;-) :-D
